import crypto from 'node:crypto';
import { ATT_HEADERS, SHEETS } from './constants';
import { appendRow, getRows, getSettings, updateRow } from './sheets';
import type { LocationPayload, SheetValue, UserRecord } from './types';
import { dateCellToKey, minutesOf, timeKey, todayKey } from './time';
import { audit } from './audit';

function pad(v:SheetValue[]){const o=v.slice();while(o.length<ATT_HEADERS.length)o.push('');return o}
export function effectiveSchedule(u:UserRecord,s:Record<string,string>){return{s1In:u.s1In||u.lateAfter||s.DEFAULT_S1_IN||s.DEFAULT_LATE_AFTER,s1Out:u.s1Out||u.punchOutFrom||s.DEFAULT_S1_OUT||s.DEFAULT_PUNCH_OUT_FROM,s2In:u.s2In||s.DEFAULT_S2_IN||'',s2Out:u.s2Out||s.DEFAULT_S2_OUT||''}}
export function nextStep(values:SheetValue[],schedule:ReturnType<typeof effectiveSchedule>){const v=pad(values);if(!v[4])return{type:'IN' as const,session:1,complete:false};if(!v[9])return{type:'OUT' as const,session:1,complete:false};if(!(schedule.s2In||schedule.s2Out))return{type:'' as const,session:1,complete:true};if(!v[22])return{type:'IN' as const,session:2,complete:false};if(!v[27])return{type:'OUT' as const,session:2,complete:false};return{type:'' as const,session:2,complete:true}}
function hav(lat1:number,lon1:number,lat2:number,lon2:number){const r=6371000,rad=(v:number)=>v*Math.PI/180,dLat=rad(lat2-lat1),dLon=rad(lon2-lon1),a=Math.sin(dLat/2)**2+Math.cos(rad(lat1))*Math.cos(rad(lat2))*Math.sin(dLon/2)**2;return r*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a))}
function validateLocation(l:LocationPayload,s:Record<string,string>){const lat=Number(l?.lat),lng=Number(l?.lng),accuracy=Number(l?.accuracy);if(![lat,lng,accuracy].every(Number.isFinite))throw new Error('Lokasi GPS tidak sah.');const max=Number(s.MAX_GPS_ACCURACY_M||120);if(accuracy>max)throw new Error(`Isyarat GPS terlalu lemah (±${Math.round(accuracy)}m). Had sistem ±${Math.round(max)}m.`);const slat=Number(s.SCHOOL_LAT),slng=Number(s.SCHOOL_LNG);if(!Number.isFinite(slat)||!Number.isFinite(slng))throw new Error('Koordinat sekolah belum ditetapkan.');const distance=Math.round(hav(lat,lng,slat,slng)),radius=Number(s.RADIUS_M||200);if(distance>radius)throw new Error(`Anda kira-kira ${distance}m dari sekolah. Had sistem ${radius}m.`);return{lat,lng,accuracy:Math.round(accuracy),distance}}
function flags(v:unknown){return[...new Set(String(v??'').toUpperCase().split(/[|,;/]+/).map(x=>x.trim()).filter(Boolean))]}
function status(f:string[]){const l=f.includes('LEWAT'),e=f.includes('BALIK AWAL');return l&&e?'LEWAT / BALIK AWAL':l?'LEWAT':e?'BALIK AWAL':'HADIR'}
async function todayRecord(u:UserRecord){const rows=await getRows(SHEETS.ATTENDANCE,'A1:AI'),date=todayKey();return rows.slice(1).map((r,i)=>({row:i+2,values:pad(r)})).find(x=>dateCellToKey(x.values[0])===date&&String(x.values[1]??'').trim().toLowerCase()===u.email)??null}
export async function attendanceToday(u:UserRecord){const settings=await getSettings(),record=await todayRecord(u),schedule=effectiveSchedule(u,settings);return{record,schedule,next:nextStep(record?.values??[],schedule),settings}}
export async function punch(u:UserRecord,type:'IN'|'OUT',location:LocationPayload,ip:string){const settings=await getSettings(),test=String(settings.SYSTEM_MODE||'REAL').toUpperCase()==='TEST',loc=test?{lat:'',lng:'',accuracy:'',distance:0}:validateLocation(location,settings),record=await todayRecord(u),schedule=effectiveSchedule(u,settings),step=nextStep(record?.values??[],schedule);if(step.complete)throw new Error('Semua rekod waktu hari ini sudah lengkap.');if(step.type!==type)throw new Error(`Turutan rekod mesti berselang. Rekod seterusnya ialah ${step.type==='IN'?'Waktu Masuk':'Waktu Balik'}.`);const now=new Date(),t=timeKey(now),nowMin=minutesOf(t),ref=type==='IN'?(step.session===1?schedule.s1In:schedule.s2In):(step.session===1?schedule.s1Out:schedule.s2Out);let ex='';if(!test&&ref){const rm=minutesOf(ref);if(type==='IN'&&nowMin>rm)ex='LEWAT';if(type==='OUT'&&nowMin<rm)ex='BALIK AWAL'}const v=pad(record?.values??[]);if(!record){v[0]=todayKey();v[1]=u.email;v[2]=u.name;v[3]=u.category}else{v[2]=u.name;v[3]=u.category}const stamp=now.toISOString();if(step.session===1&&type==='IN'){v[4]=stamp;v[5]=loc.lat;v[6]=loc.lng;v[7]=loc.distance;v[8]=loc.accuracy;v[19]=ip}if(step.session===1&&type==='OUT'){v[9]=stamp;v[10]=loc.lat;v[11]=loc.lng;v[12]=loc.distance;v[13]=loc.accuracy;v[20]=ip}if(step.session===2&&type==='IN'){v[22]=stamp;v[23]=loc.lat;v[24]=loc.lng;v[25]=loc.distance;v[26]=loc.accuracy;v[32]=ip}if(step.session===2&&type==='OUT'){v[27]=stamp;v[28]=loc.lat;v[29]=loc.lng;v[30]=loc.distance;v[31]=loc.accuracy;v[33]=ip}const f=flags(v[34]);if(ex&&!f.includes(ex))f.push(ex);v[34]=f.join('|');v[14]=status(f);v[15]=test?'TEST':'GPS';v[18]=stamp;if(record)await updateRow(SHEETS.ATTENDANCE,record.row,v);else await appendRow(SHEETS.ATTENDANCE,v);await audit(u.email,`REKOD_${type==='IN'?'MASUK':'KELUAR'}_SESI_${step.session}`,u.email,`${ex||'TEPAT MASA'}; mod=${test?'TEST':'REAL'}; jarak=${loc.distance}m; IP=${ip||'-'}`);if(ex)await appendRow(SHEETS.TIME_REVIEW,[crypto.randomUUID(),stamp,todayKey(),u.email,u.name,u.jobTitle,u.category,ex,step.session,t,ref,'MENUNGGU','','','','']);return{ok:true,message:`Rekod waktu ${type==='IN'?'Masuk':'Balik'} berjaya${ex?` — ${ex}`:''}.`,exception:ex,distanceM:loc.distance}}
export async function monthRecords(u:UserRecord,month:string){if(!/^\d{4}-\d{2}$/.test(month))throw new Error('Bulan tidak sah.');const rows=await getRows(SHEETS.ATTENDANCE,'A1:AI');return rows.slice(1).filter(r=>dateCellToKey(r[0]).startsWith(month)&&String(r[1]??'').trim().toLowerCase()===u.email).map(r=>({date:dateCellToKey(r[0]),in1:String(r[4]??''),out1:String(r[9]??''),in2:String(r[22]??''),out2:String(r[27]??''),status:String(r[14]??''),reason:String(r[17]??'')}))}
